# Generated by Django 5.1 on 2024-08-23 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_produit_old_price_alter_produit_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='user',
        ),
        migrations.AlterField(
            model_name='produit',
            name='old_price',
            field=models.FloatField(blank=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyApp.userr')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.produit')),
            ],
        ),
    ]
