# Generated by Django 5.1 on 2024-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_produit_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_vente',
            field=models.DateField(blank=True, null=True),
        ),
    ]
