# Generated by Django 5.1 on 2024-08-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_produit_date_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='date_vente',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='date_vente',
            field=models.DateField(blank=True, null=True),
        ),
    ]
